#!/bin/bash

# Subprojects list
subprojects=(
    auth
    products
    users
    client
    core
)

# Update Main Repository
command git pull https://github.com/benzene-tech/inventory-management.git
command git fetch

for subp in ${subprojects[@]}; do
    if command cd $subp > /dev/null 2>&1; then
        # Update Git Repository
        command git pull https://github.com/benzene-tech/inventory-management-$subp.git
        command git fetch
    else
        # Clone Git Repository
        command git clone https://github.com/benzene-tech/inventory-management-$subp.git $subp
    fi

    # Build Project
    # Change Working Directory to Main Repo
    command cd ..
done
