#!/bin/bash

# Subprojects list
subprojects=(
    auth
    products
    users
    client
    core
)

# Update Main Repository
command git pull origin main

for subp in ${subprojects[@]}; do
    if command cd $subp > /dev/null 2>&1; then
        # Update Git Repository
        command git pull origin main
        
        # Build Project
        # Change Working Directory to Main Repo
        command cd ..
    else
        # Clone Git Repository
        command git clone --single-branch https://github.com/benzene-tech/inventory-management-$subp.git $subp
    fi
done
