apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dpl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: avidyarth/inventory-management-auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-svc:27017/auth"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
