apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: inventory-management.com
      http:
        paths:
          - pathType: Prefix
            path: "/api/auth/?(.*)"
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000
          - pathType: Prefix
            path: "/api/products/?(.*)"
            backend:
              service:
                name: products-svc
                port:
                  number: 3000
          - pathType: Prefix
            path: "/?(.*)"
            backend:
              service:
                name: client-svc
                port:
                  number: 3000
