apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-dpl
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: avidyarth/inventory-management-products
          env:
            - name: MONGO_URI
              value: "mongodb://products-mongo-svc:27017/products"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: products-svc
spec:
  selector:
    app: products
  ports:
    - port: 3000
      targetPort: 3000
