apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-dpl
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: avidyarth/inventory-management-users
          env:
            - name: MONGO_URI
              value: "mongodb://users-mongo-svc:27017/users"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: RABBITMQ_URI
              value: "amqp://rabbitmq-svc:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  selector:
    app: users
  ports:
    - port: 3000
      targetPort: 3000
